# Get the data

In [1]:
import mysql.connector

conn = mysql.connector.connect(
    host="18.136.157.135",
    user="dm_team5",
    password="DM!$!Team!520@4!23&",
    database="project_profit_analysis"
)

print("Connected Successfully")

Connected Successfully

In [2]:
cursor=conn.cursor()
cursor.execute("SHOW TABLES")
tables=cursor.fetchall()
for table in tables:
    print(table[0])

startup

In [3]:
import pandas as pd
query="SELECT * FROM startup"
df=pd.read_sql(query,conn)

C:\Users\iambh\AppData\Local\Temp\ipykernel_21468\493891707.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query,conn)

In [4]:
csv_file_path = "startup_data.csv"
df.to_csv(csv_file_path, index=False)  # index=False avoids saving the row numbers

print(f"CSV file saved at {csv_file_path}")

CSV file saved at startup_data.csv

In [5]:
df.head()

    RD_Spend  Administration  Marketing_Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [6]:
df.describe()

            RD_Spend  Administration  Marketing_Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [7]:
df.shape

(50, 5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RD_Spend         50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing_Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [9]:
df.isnull().sum()

RD_Spend           0
Administration     0
Marketing_Spend    0
State              0
Profit             0
dtype: int64

# performing linear regression model

In [10]:
# preparing the data 
x=df[['RD_Spend','Administration','Marketing_Spend']]
y=df['Profit']

In [11]:
# train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
# creating linear regression model
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [13]:
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 54071.875745990845
Coefficients: [ 0.80377928 -0.06792917  0.03124155]

In [15]:
import numpy as np
x=np.array([
    [21892.92, 81910.77, 164270.7],
    [23940.93, 96489.63, 137001.1]
])
predicted_profit=model.predict(x)
print(predicted_profit)

[71236.89079079 71040.76440737]

C:\Users\iambh\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(